apiVersion: v1
data:
  config.kafka.yaml: |
    data_rate: 300000
    period: 1000
    chunk_size: 900000

    pattern:
        - type: burst
        - fraction: 0.7
        - distribution: 0.3

    data_source:
      type: "csv"
      file: "data/data.csv"
      #type: "image_folder"
      #file: "/app/data/img"
      #encoding: "base64"

    duration: 60
    host: "0.0.0.0"
    ports:
      - 9090

    mqtt:
      enabled: false
      host: "mosquitto"
      port: 1883
      topic: "bid"

    kafka:
      enabled: true
      brokers: "my-cluster-kafka-bootstrap.kafka.svc:9092"
      topic: "bid"
      properties:
        compression.type: "lz4"
        linger.ms: "5"
        batch.size: "1048576"
        acks: "1"
        queue.buffering.max.messages: "1000000"
        queue.buffering.max.kbytes: "1048576"

    zipf:
      period_ms: 1000
      s: 1.4
      stochastic: true

  config.mqtt.yaml: |
    data_rate: 1
    period: 1000
    chunk_size: 1000

    pattern:
      - type: burst
      - fraction: 0.5
      - distribution: 0.5

    data_source:
      type: "image_folder"
      file: "/app/data/img"
      encoding: "base64"

    duration: 60
    host: "0.0.0.0"
    ports:
      - 8080
      - 8081
      - 8082

    mqtt:
      enabled: true
      host: "mosquitto"
      port: 1883
      topic: "bid"

    zipf:
      period_ms: 1000
      s: 1.4
      stochastic: true
  config.yaml: |
    data_rate: 300000
    period: 1000
    chunk_size: 600000

    pattern:
        - type: burst
        - fraction: 0.7
        - distribution: 0.3

    data_source:
      type: "csv"
      file: "data/sps30_2021_2022_parsed_timestamp_comma_separated_clean.csv"
      #type: "image_folder"
      #file: "/app/data/img"
      #encoding: "base64"

    duration: 60000
    host: "0.0.0.0"
    ports:
      - 9090
      - 9091
    #  - 8082

    mqtt:
      enabled: false
      host: "mosquitto"
      port: 1883
      topic: "bid"

      kafka:
        enabled: true
        brokers: "localhost:9092"
        topic: "bid"

    zipf:
      period_ms: 1000
      s: 1.4
      stochastic: true
kind: ConfigMap
metadata:
  name: datagen-config
  namespace: default
