apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datagen
  template:
    metadata:
      labels:
        app: datagen
    spec:
      containers:
        - name: datagen
          image: datagen:local
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /app/config/
              name: config

            - mountPath: /app/data
              name: data
          env: 
            - name: DATAGEN_BIN
              value: /usr/local/bin/datagen_shared
            - name: DATAGEN_CONFIG
              value: /app/config/config.kafka.yaml
      volumes:
        - name: config
          configMap:
            name: datagen-config

        - name: data
          hostPath:
            path: /home/docker/dataset/
            type: DirectoryOrCreate
