apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: luftdaten-job
spec:
  image: luftdaten-flink:local

  flinkVersion: v1_19

  serviceAccount: flink

  jobManager:
    resource:
      memory: "1024m"
      cpu: 1

  taskManager:
    resource:
      memory: "4096m"
      cpu: 4

  job:
    jarURI: local:///opt/flink/usrlib/luftdaten-flink-0.1.jar
    entryClass: com.yourname.luftdaten.jobs.Q2CoarseParticleDominanceFilterSPS30
    args:
      - "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
      - "bid"
      - "rtracker"
      - "9000"
    parallelism: 2
    upgradeMode: stateless

  flinkConfiguration:
    execution.checkpointing.interval: "30s"
    execution.checkpointing.storage: filesystem
    high-availability.type: kubernetes
    high-availability.storageDir: file:///opt/flink/checkpoints/ha
    state.checkpoints.dir: file:///opt/flink/checkpoints
    state.backend: hashmap

    rest.profiling.enabled: "true"

    taskmanager.numberOfTaskSlots: "4"

    job.autoscaler.enabled: "true"
    job.autoscaler.scaling.enabled: "true"

    # target utilization
    job.autoscaler.target.utilization: "0.7"

    # stabilize scaling decisions
    job.autoscaler.stabilization.interval: "30s"
    job.autoscaler.metrics.window: "1m"
    job.autoscaler.scaling.interval: "30s"
    job.autoscaler.max-parallelism: "8"
